baseURL: "https://myong.dev"
languageCode: "ko-kr"
title: "Dev Logs | DevMyong"
pygmentsstyle: 'monokai'
paginate: 6
theme: "novela-hugo"
disqusShortname: "devmyong"
social:
  #twitter: "#"
  github: "https://github.com/devmyong"
  #instagram: "#"
  linkedin: "https://www.linkedin.com/in/daemyeong-kwon-b1b95618b/"
  #dribbble: "#"
  #youtube: "#"
taxonomies:
  author: authors
